#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "ESP32-C5-DevKitC-1-N8R8"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32C5"
#endif

#define MICROPY_HW_ENABLE_USBDEV (0)
#define MICROPY_HW_USB_CDC (0)
#define MICROPY_HW_USB_MSC (0)
#define MICROPY_HW_ESP_USB_SERIAL_JTAG (1)
#define MICROPY_HW_ENABLE_UART_REPL (0)
#define MICROPY_HW_ENABLE_SDCARD (0)

#define MICROPY_PY_ESPNOW (0)
#define MICROPY_PY_MACHINE_I2S (0)

#define MICROPY_PY_NETWORK_WLAN (1)

#ifndef MICROPY_PY_BLUETOOTH
#define MICROPY_PY_BLUETOOTH (0)
#endif
