/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "sdkconfig.h"

#ifndef OMV_NO_GPL
#define OMV_NO_GPL
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_BINARY_OPS
#define IMLIB_ENABLE_BINARY_OPS
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_MATH_OPS
#define IMLIB_ENABLE_MATH_OPS
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_LAB_LUT
#define IMLIB_ENABLE_LAB_LUT
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_QRCODES
#define IMLIB_ENABLE_QRCODES
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_APRILTAGS
#define IMLIB_ENABLE_APRILTAGS

#if CONFIG_ESP_VISION_CORE_APRILTAG_TAG16H5
#define IMLIB_ENABLE_APRILTAGS_TAG16H5
#endif

#if CONFIG_ESP_VISION_CORE_APRILTAG_TAG25H7
#define IMLIB_ENABLE_APRILTAGS_TAG25H7
#endif

#if CONFIG_ESP_VISION_CORE_APRILTAG_TAG25H9
#define IMLIB_ENABLE_APRILTAGS_TAG25H9
#endif

#if CONFIG_ESP_VISION_CORE_APRILTAG_TAG36H10
#define IMLIB_ENABLE_APRILTAGS_TAG36H10
#endif

#if CONFIG_ESP_VISION_CORE_APRILTAG_TAG36H11
#define IMLIB_ENABLE_APRILTAGS_TAG36H11
#endif

#if CONFIG_ESP_VISION_CORE_APRILTAG_ARTOOLKIT
#define IMLIB_ENABLE_APRILTAGS_ARTOOLKIT
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_HIGH_RES_APRILTAGS
#define IMLIB_ENABLE_HIGH_RES_APRILTAGS
#endif

#if CONFIG_ESP_VISION_CORE_ENABLE_FINE_APRILTAGS
#define IMLIB_ENABLE_FINE_APRILTAGS
#endif

#endif /* CONFIG_ESP_VISION_CORE_ENABLE_APRILTAGS */
